cubes:
- name: field_configurations
  sql_table: public.field_configurations
  title: Field Configurations
  description: Таблица field_configurations
  joins:
  - name: organizations
    sql: '{CUBE}.organization_id = {organizations}.id'
    relationship: many_to_one
    title: Организация
    description: Идентификатор организации
  dimensions:
  - name: id
    sql: id
    type: number
    primary_key: true
    title: id
    description: id (integer)
  - name: name
    sql: name
    type: string
    title: Name
    description: name (character varying)
  - name: description
    sql: description
    type: string
    title: Description
    description: description (text)
  - name: created_at
    sql: created_at
    type: time
    title: Created At
    description: created_at (timestamp without time zone)
  measures:
  - name: count
    type: count
    title: Количество
    description: Общее количество записей в таблице Field Configurations
