cubes:
- name: field_configuration_items
  sql_table: public.field_configuration_items
  title: Field Configuration Items
  description: Таблица field_configuration_items
  joins:
  - name: field_configurations
    sql: '{CUBE}.configuration_id = {field_configurations}.id'
    relationship: many_to_one
    title: Конфигурация поля
    description: Идентификатор конфигурации полей, связанных с конкретным элементом
  - name: custom_field_contexts
    sql: '{CUBE}.field_id = {custom_field_contexts}.id'
    relationship: many_to_one
    title: Контекст поля
    description: Дополнительная информация о контексте, связанном с данным полем
  dimensions:
  - name: id
    sql: id
    type: number
    primary_key: true
    title: id
    description: id (integer)
  - name: is_hidden
    sql: is_hidden
    type: boolean
    title: Is Hden
    description: is_hidden (boolean)
  - name: is_required
    sql: is_required
    type: boolean
    title: Is Required
    description: is_required (boolean)
  - name: renderer
    sql: renderer
    type: string
    title: Renderer
    description: renderer (character varying)
  - name: description
    sql: description
    type: string
    title: Description
    description: description (text)
  - name: created_at
    sql: created_at
    type: time
    title: Created At
    description: created_at (timestamp without time zone)
  measures:
  - name: count
    type: count
    title: Количество
    description: Общее количество записей в таблице Field Configuration Items
